spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${MY_CLIENT_ID}
            client-secret: ${MY_KAKAO_CLIENT_SECRET}
            redirect-uri: ${MY_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile, account_email
        provider:
          kakao:
            authorization-uri: ${AUTHORIZATION_URI}
            user-info-uri: ${USER_INFO_URI}
            token-uri: ${TOKEN-URI}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  secret: ${SECRET_KEY}
  access-token-validity-in-milliseconds: ${ACCESS_TOKEN_EXPIRE_TIME}

kakao:
  logout-redirect-uri: ${MY_LOGOUT_REDIRECT_URI}
  unlink-url: ${UNLINK_URI}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${BUCKET_ACCESS_KEY}
      secret-key: ${BUCKET_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cron: ${CRON_TIME}


server:
  port: 8443
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: pkcs12
    key-alias: tomcat
    enabled: true

#  main:
#    allow-bean-definition-overriding: true
#
#

